### ISSUE TITLE
unnecessary Scrollbar

### ISSUE THREAD

**Issue by jlnrrg** [doersino/nyum#16]
![image](https://user-images.githubusercontent.com/77293597/115348971-9373f480-a1b3-11eb-97c0-7aac05e19812.png)

I noticed that in the recent version a vertical and horizontal scrollbar was added to the icons in the top right corner.
For a smaller screen this is a great idea, but imo it would look better if it stays hidden, when it can not be used.

**Comment by doersino** [comment]
Right, that was intended to improve things on small screens, but I keep forgetting that not everyone uses an OS that hides scroll bars by default. I'll roll this back.
