### ISSUE TITLE
Picture in Overview page

### ISSUE THREAD

**Issue by jlnrrg** [doersino/nyum#17]
It might be a neat optical feature to include the image in the overview page if it exists.

![Screenshot from 2021-04-20 10-29-49](https://user-images.githubusercontent.com/77293597/115364400-a7275700-a1c3-11eb-83c8-e28b29e24adf.png)

**Comment by doersino** [comment]
There is (at your previous suggestion, I believe) – take a look at `config.yaml`.

The layout you’re proposing is tricky since most images won’t be nearly square – on recipe pages, it looks best when they’re rather wide.

**Comment by jlnrrg** [comment]
Ok, again sorry.
It is hard to keep track of all the new feature you've put in since I last visited :see_no_evil: (it is so much)

Maybe a recipe in your example page where every possible feature is checked might be useful.
(I think you tried this with "Pan-Fried Perilla Leaves" already a little)

**Comment by jlnrrg** [comment]
nvm. I looked at the wrong place.

**Comment by jlnrrg** [comment]
@doersino 
imo the pictures rn get way to big to deliver a pleasant viewing experience.
![image](https://user-images.githubusercontent.com/77293597/115368910-d93ab800-a1c7-11eb-973a-f0c2df0d7baf.png)

Concerning the square part, that was mainly bc of my bad drawing talent. (16:9 is just fine)
And for recipes without a picture a placeholder picture could be provided by the user.

**Comment by doersino** [comment]
Better late than never!

<img width="1043" alt="Screenshot 2021-05-25 at 11 18 15" src="https://user-images.githubusercontent.com/1944410/119473187-37b90000-bd4b-11eb-82df-cc6f0854772f.png">
