### ISSUE TITLE
Whole ListItem clickable

### ISSUE THREAD

**Issue by jlnrrg** [doersino/nyum#18]
overview page -> extend `<a></a>` over the whole ListItem and not just the title,
so the whole item is clickable

(I used the web version on a desktop pc, might be implemented already on mobile, I'm not sure)

**Comment by doersino** [comment]
At least in search results, I've already implemented this a while ago.

As I've written in #1:

> Inside the main portion of the index page, the user could have added their own links as part of recipe descriptions. Wrapping the link to the recipe around the whole list item would render such links inoperable.

**Comment by jlnrrg** [comment]
@doersino sorry I overlooked this.
I think what you describe is a relative small use case, as one can always link a source in the  source tag.
But I can understand the hesitation because it would introduce a limit here.
Would it be possible to check if the text includes a link and then act respectively?
