### ISSUE TITLE
add Readme Table of Content

### ISSUE THREAD

**Issue by jlnrrg** [doersino/nyum#19]
With all the great work you've put into the readme,
it reached a size by now, which would benefit from a table of content.

This would be especially beneficial to quickly jump to the list of possible yaml fields.

**Comment by doersino** [comment]
No need, GitHub has recently added a feature that takes care of this in the interface: https://github.blog/changelog/2021-04-13-table-of-contents-support-in-markdown-files/

**Comment by jlnrrg** [comment]
The more you know :smile: 
thanks for the link
