### ISSUE TITLE
UTF-8: cut: the delimiter must be a single character

### ISSUE THREAD

**Issue by kseistrup** [doersino/nyum#2]
Building the demo site, I see the following error messages:

```sh
cut: the delimiter must be a single character
Try 'cut --help' for more information.
```

Hm…, let's see where `cut` gets into it:

```sh
$ rg cut
_site/cheesebuldak.html:            <p>Cut meat into <code>2-3 cm</code> cubes and mix into the marinade.</p>
build.sh:for CATEGORY in $(echo "$CATS" | cut -d§ -f2- | sort | uniq | (cat -; echo "$UNCATEGORIZED_LABEL")); do
build.sh:            C_CAT=$(echo "$C" | cut -d§ -f2-)
build.sh:        BASENAME=$(echo "$C" | cut -d§ -f1)
build.sh:        C_CAT=$(echo "$C" | cut -d§ -f2-)
_recipes/cheesebuldak.md:> Cut meat into `2-3 cm` cubes and mix into the marinade.
README.md:Apart from the translation of Markdown into HTML, which is a fairly self-explanatory `pandoc` call, and the `config.yaml` shenanigans, which are merely a medium-sized mess: I wanted to **build an index page listing all recipes, but ordered by category** and with cute spicy/vegan/etc. icons.
README.md:3. Employing a `cut`-`sort`-`uniq` pipeline to distill a list of unique categories.
```

So:

```sh
$ printf '§' | hexdump -C
00000000  c2 a7                                             |..|
00000002
```

Apparently `cut` sees ‘§’ as multibyte and barfs.

```sh
$ uname -a
Linux home 5.11.7-arch1-1 #1 SMP PREEMPT Wed, 17 Mar 2021 16:59:58 +0000 x86_64 GNU/Linux
$ cut --version | head -1
cut (GNU coreutils) 8.32
$ printf 'LC_ALL=%s, LANG=%s\n' "$LC_ALL" "$LANG"
LC_ALL=en_DK.UTF-8, LANG=en_GB.UTF-8
```

**Comment by doersino** [comment]
Oops, I used that character under the assumption that it's among those characters represented by a single byte in any ASCII/Unicode-based system – clearly I need to brush up on my ASCII tables! 😉

Interesting, BSD/macOS `cut` seems to deal with multi-byte delimiters just fine.

Thank you for doing the investigation work for me! I've chosen a different character now – does that fix the issue for you?

**Comment by kseistrup** [comment]
Thanks, that works (I'm a little puzzled that the ‘#’ isn't parsed as a comment character, though) — thanks for fixing it so soon!

**Comment by doersino** [comment]
That's true, it could be iffy in other/older versions of Bash. The separator should be very unlikely to occur in filenames, otherwise I would've just gone down the CSV route and used a comma.

Come to think of it, a space seems like a good one.

**Comment by kseistrup** [comment]
Or perhaps just

```sh
| cut -d\# …    # escape the delimiter
| cut -d '#' …  # enclose the delimiter in single quotes
```

When reading the script and templates as a human, it can be difficult to distinguish a SPACE and a TAB at a glance.

Sorry for being so difficult.

**Comment by doersino** [comment]
Also a good option, but I think I'll just leave it as a space for now.

No worries about being difficult – I wrote a static site generator as a Bash script, so I'm practically asking for it. 😉
