### ISSUE TITLE
unexpected "{"

### ISSUE THREAD

**Issue by jlnrrg** [doersino/nyum#3]
Steps:
- clone project
- on Ubuntu 20.04.2 LTS run `sudo apt install -y pandoc`
- check pandoc version (= 2.5)
- `bash build.sh` 

<details>
<summary>Error log</summary>

```
Resetting _site/ and _temp/...
↪ mkdir -p _site/
↪ touch _site/dummy.txt
↪ rm -r _site/
↪ mkdir -p _site/
↪ mkdir -p _temp/
↪ touch _temp/dummy.txt
↪ rm -r _temp/
↪ mkdir -p _temp/
Copying assets...
↪ cp -r _assets/ _site/assets/
Copying static files...
↪ cp _recipes/cheesebuldak.jpg _site/
↪ cp _recipes/strawberrysmoothie.jpg _site/
Building recipe pages...
↪ pandoc _recipes/cheesebuldak.md --metadata-file config.yaml --metadata updatedtime=2021-03-25 --template _templates/recipe.template.html -o _site/cheesebuldak.html
"template" (line 4, column 6):
unexpected "{"
expecting letter
```
</details>

**Comment by doersino** [comment]
Thanks for posting the error log and specifying the Pandoc and Ubuntu versions you're running – that helped a lot!

The point in the template at which the error occurred is where `head.partial.html` is loaded in. After taking a look at [the changelog](https://github.com/jgm/pandoc/blob/master/changelog.md#pandoc-28-2019-11-22), it seems like partials haven't been a Pandoc feature for very long: They were added in version 2.8, released in November 2019 – so it's no wonder that an error is thrown in version 2.5, which was the most recent release when your OS was released. More recent versions of Ubuntu [apparently](https://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=pandoc&searchon=names) offer newer versions of Pandoc. I'll add a note about this to the readme!

I suggest downloading a binary from here: https://github.com/jgm/pandoc/releases/latest
