### ISSUE TITLE
Expose all labels in config.yaml

### ISSUE THREAD

**Issue by jlnrrg** [doersino/nyum#6]
Please consider exposing all used labels in the config.yaml, so one can build a complete german version for example.
I noticed these yet to be done:
- 4 **SERVING**
- 1 **HOUR**

**Comment by doersino** [comment]
Those aren't preset labels – they're spelled out in the recipe metadata, *e.g.*, [here](https://github.com/doersino/nyum/blob/main/_recipes/veganchocolatecake.md). That enables using different terms depending on what's appropriate for the recipe in question, e.g. the size of the required springform for a cake, or "minutes" for a quick recipe.

Just write 'em in German. 😉

**Comment by jlnrrg** [comment]
That was totally my mistake, sorry for wasting your time.
I think the footer "UPDATED ON" would nevertheless fit the label collection 😀

**Comment by doersino** [comment]
True. I'll add that to my list of changes to make this weekend!
