### ISSUE TITLE
Support for more out of the box attributes

### ISSUE THREAD

**Issue by jlnrrg** [doersino/nyum#7]
I noticed that rn these attributes are supported:
- spicy
- veggie
- vegan
- favorite
- size
- time
- author
- source

It would be great if additional diets would be supported (e.g. keto).
And dish information like
- kcal
- protein
- fat
- carbohydrates

**Comment by doersino** [comment]
Additional diets *are* supported – if you adhere to a keto diet, that'll manifest in the kinds of recipes you cook regularly, which will determine which recipes you decide to write down. This tool isn't intended as a multilingual, fully-featured recipe database, so I don't think everything needs to be formalized.

I'd be open to adding nutrition labels, but the [icon package](https://tabler-icons.io) used here doesn't really provide much in that area, so they won't fit in along with the row of spicy, vegan, size, author/source labels. Perhaps a different layout makes sense for them – something like this (just a quick prototype)?

![Screenshot 2021-03-25 at 17 59 15](https://user-images.githubusercontent.com/1944410/112512761-f2e90b00-8d93-11eb-882f-272603fb95ec.png)

Another question would be which units the nutrition data should be specified in – grams, percentage of recommended daily intake, something else? Hard to pin down what the right choice would be.

**Comment by jlnrrg** [comment]
I personally would prefer the items under each other, so maybe right of the description

![112512761-f2e90b00-8d93-11eb-882f-272603fb95ec](https://user-images.githubusercontent.com/77293597/112513814-ff219800-8d94-11eb-9266-493d3447de9b.png)

For the data, I would handle it like every other measurement and just use string. This gives the most flexibility and the data isn't processed anywhere anyway.

**Comment by doersino** [comment]
I think that looks a bit cluttered. I've added it to my list and will work something out over the weekend. 😉

**Comment by doersino** [comment]
Just so I'm aware: Which nutrition labels are important to you? Just the four you mentioned further up, or are there more?

**Comment by jlnrrg** [comment]
Hard to tell, as I think this will grow by request of me or others.
For now I would argue for:
- sweet
- salty
- sour/ bitter
- umami
- no sugar
- protein rich

for the nutrition labels I think that these 4 are enough as they are the most common ones.

**Comment by doersino** [comment]
The trouble with adding *those* labels is that there really aren't any commonly understood icons for concepts like "sweet", "salty", "sour", "bitter", "umami", "no sugar", and "protein rich", so they won't fit in with the already existing "spicy", "vegan, and "meat" labels (text-only might look decent enough on recipe pages, but not on the index or in search, where *only* the icons are shown to save space).

Nutrition labels are easier since they'd logically be in a different section.

**Comment by jlnrrg** [comment]
I disagree partly, because there are multiple commonly understood icons for the concepts.
For sweet it could be honey, sweets, etc like [this](https://www.pixtastock.com/illustration/41066104)
For the rest something like [this](https://www.pinterest.pt/pin/411868328404327114/?send=true), but I agree that it highly depends on the icon pack you use. Which is it btw?

For no sugar I'd say crossed out sugar cubes and for high protein anything like [these](https://www.google.de/search?q=protein+icon&tbm=isch)

**Comment by doersino** [comment]
> I agree that it highly depends on the icon pack you use. Which is it btw?

This one: https://tabler-icons.io. (`ice-cream-2` might work for "sweet", but that's about it).

The icons contained Pinterest image you linked seems sensible (with the exception of the sausage for "umami"), but they don't match the style, and of course I've got no idea whether they've been released under a license that would allow me to use them here.

**Comment by jlnrrg** [comment]
I agree that the icon pack is a major issue and would propose to postpone this issue, for when usable icons will be released. 
If you'd like to decide for specific icons, we could propose them at the icon pack, otherwise just waiting is also fine for me :smile:.

**Comment by doersino** [comment]
They've [done it](https://github.com/tabler/tabler-icons/issues/122#issuecomment-821990705)! I'll incorporate them sometime next week.
